[features]
seeds = false
skip-lint = false
[programs.devnet]
mint_nft = "3C1UFAwxLFK52J3drUMRia86Wpo98oxvR2JNZsgzJrjJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/ascespool/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
